### ISSUE TITLE
Slow return from Player view back to Article list

### ISSUE THREAD

**Issue by dylano** [MozScout/scout-ios#20]
When leaving the Player view by touching the back button, the list of titles is being refreshed with a call to the Scout server. This makes it quite slow to see the titles again. 

I'd suggest that we return to the cached view of the titles and instead enable a manual refresh of the list via a pull-down action on the list view. I don't think it will be common for users to add new titles to their list while the player view is active -- certainly not frequently enough to justify a refresh every time we leave the player screen.

**Comment by Alegero** [comment]
done

**Comment by dylano** [comment]
Confirmed. This is *much* better!
