### ISSUE TITLE
Need a spinner when switching between article modes in Player view

### ISSUE THREAD

**Issue by dylano** [MozScout/scout-ios#21]
When in Player view and using the links to switch between "Full Length" and "Skim", it can take a few seconds to generate/download/play the other file. We need a spinner indicator there to let the user know we're working on it

**Comment by Alegero** [comment]
done. (Spinner color is white. Please let me know if we should use another one)

**Comment by dylano** [comment]
Yes, definitely need a different color. I'm testing on an iPad so the middle of the screen is in the text area with the white background and the spinner is invisible except for very small overlaps with the black text. On iPhone I assume this is presented over the top of the article image so it shows better.

@tamarahills Maybe something else from the Mozilla color palette that would give better visibility against different backgrounds?

**Comment by tamarahills** [comment]
Discussed with Abe.  Abe to mock something up to have the bottom box replaced with a spinner during the resynthesizing period so we can reliably see it.

**Comment by tamarahills** [comment]
![scout v3 - light - player - toggle](https://user-images.githubusercontent.com/7558944/40942437-052620dc-6803-11e8-9f81-bc375556c34d.jpg)

**Comment by tamarahills** [comment]
- Replace the article progress bar with a loading icon and message.
- Grey out the Play and jump forward/back buttons. We may want to grey out other controls if they're unavailable?

**Comment by Alegero** [comment]
done

**Comment by dylano** [comment]
Re-opening:
* The spinner/text does not appear directly above the title as indicated in the screen shot above, but instead is appearing in the bottom left area of the image on my device. See video at https://photos.app.goo.gl/kUYXtiKMS7tQXluk2
* There is a typo in the text: "Prepearing" instead of "Preparing"

**Comment by dylano** [comment]
Video showing text position problem on iPhone SE: https://photos.app.goo.gl/XjMi3Epusx9JJuoc9

**Comment by Alegero** [comment]
done. (tested on iPhone SE too)

**Comment by dylano** [comment]
Verified, looks good! 👍
