### ISSUE TITLE
Scout UI: buttons/hit targets on title list need to be larger

### ISSUE THREAD

**Issue by dylano** [MozScout/scout-ios#27]
When trying to play or skim an article from the main list, I frequently miss the Play or Skim button and instead collapse the controls. We need to either give them more real estate or give a larger touch area if that's possible.

**Comment by tamarahills** [comment]
Spoke to Abe.  This should have a height 44px.

**Comment by dylano** [comment]
Looks good, this is working much better for me on build 10.
