### ISSUE TITLE
Scout UI: Need a way to refresh article list

### ISSUE THREAD

**Issue by dylano** [MozScout/scout-ios#28]
Right now, the only way to refresh the article list is to restart the app. We need a pull-down action or button to trigger a manual refresh.

**Comment by tamarahills** [comment]
Yes, we want to add this.  Tamara to add a story.

**Comment by iukhno** [comment]
@tamarahills we added task for this improvement https://github.com/MozScout/scout-ios/issues/24
For better performance of this task , we need completed task https://github.com/MozScout/scout-ios/issues/25 on server side

**Comment by dylano** [comment]
Verified (and duplicate of #24)
