### ISSUE TITLE
Scout UI: Need better differentiation for Full Length / Skim links in player view

### ISSUE THREAD

**Issue by dylano** [MozScout/scout-ios#29]
Once you have begun listening to an article, there is no visual indicator of whether you are in Full or Skim mode. We need to do a better job of highlighting the active mode, or maybe just provide a single link with a direction like "Switch to Skim"  (<-- insert better words here)

**Comment by tamarahills** [comment]
See Abe's mockup that shows bold and underlined for what you are listening to.

**Comment by dylano** [comment]
![image](https://user-images.githubusercontent.com/2423092/40937526-cad02180-67f3-11e8-8038-ecf6c1a71c8f.png)

**Comment by dylano** [comment]
Verified.
