### ISSUE TITLE
Change the progress bar to be the bar underneath "Read Article" and above the Title

### ISSUE THREAD

**Issue by tamarahills** [MozScout/scout-ios#32]
Let's change the separator bar above the title to be the progress bar location.  Also, we like that it does not extend all the way to the edge of the screen... so we want to keep that padding there.

**Comment by tamarahills** [comment]
![scout v3 - light - player](https://user-images.githubusercontent.com/7558944/40940558-0842b542-67fd-11e8-87da-f106e5376a8d.jpg)

**Comment by dylano** [comment]
Verified.
