### ISSUE TITLE
Zoom / Crop image on player screen to fill available space

### ISSUE THREAD

**Issue by dylano** [MozScout/scout-ios#39]
On the player screen, the article's image view should be zoomed such that the entire image space is filled with the picture and any black bars on sides or top/bottom are eliminated. 

Full image (current state):
![img-origina](https://user-images.githubusercontent.com/2423092/41116603-ac506578-6a3f-11e8-85c0-4d0f752f8e69.png)

Desired presentation:
![img-zoom](https://user-images.githubusercontent.com/2423092/41116626-bff08e64-6a3f-11e8-8372-674bc871bf92.png)

**Comment by dylano** [comment]
Note: do not scale/stretch the full image to fit in the space. do not change the aspect ratio of the original image.

![img-stretch](https://user-images.githubusercontent.com/2423092/41116717-f1560696-6a3f-11e8-8c9a-4bc44f8f90ce.png)

**Comment by iukhno** [comment]
we consider by default to show same image that was send from server and keep original proportion
in case we should zoom it to remove black area, this would mean that some important parts of image could be lost. app won't know what part of image is important and what is not. All images would be processed in absolutely same way. @dylano

**Comment by dylano** [comment]
@iukhno I understand -- the request is just to zoom in on the center of the image until it fills the view, not to perform any analysis on the proper part of the image to show. Yes many images will lose detail from the edges but audio is the real purpose of the app so we don't mind losing information from the picture.

**Comment by Alegero** [comment]
done

**Comment by dylano** [comment]
👍 Verified. This looks great.
