### ISSUE TITLE
Create Tabs for Listen, Notes, and Subscriptions

### ISSUE THREAD

**Issue by tamarahills** [MozScout/scout-ios#53]

**Comment by Oksanayaz** [comment]
Acceptance  criteria:
1. User can navigate among tabs 'Listen', 'Notes' and 'Subscriptions' from the bottom Tab bar.
2. If tab is not finished yet, User can see only Top bar and Tab bar on the screen.
3. If tab is finished, User can see the tab content.

**Comment by tamarahills** [comment]
Update Notes 3/1:
Top navigation bar will be reused on multiple tabs -- in progress... near completion.
Scrolling up and down thru content -- in progress..  Adding ability to refresh the data
pull up -- will hide the top navigation bar
