### ISSUE TITLE
Create Listen tab

### ISSUE THREAD

**Issue by tamarahills** [MozScout/scout-ios#54]

**Comment by Oksanayaz** [comment]
### Acceptance criteria:

1. User can see the playlist of  articles and Podcasts based on selected topics (preferences).
2. The Top bar slides away on scroll up.
3. User can refresh the playlist with native iOS refreshment on pull down.
4. User can remove items in bulk in Edit mode.
5. User can use swipes for:
* Swipe left - for removal of a single item.
* Swipe right - to play summary (needs Player implementation).
6.  User can listen to an item full version or summarized version for article (needs Player implementation).

**Comment by tamarahills** [comment]
Update 3/1
In progress - 
APIs is ready.  Missing fields are added.
Ability to swipe left/right implemented - completed.
No api integration yet.  
Ability to remove items.

**Comment by tamarahills** [comment]
User can see the playlist of articles and Podcasts based on selected topics (preferences). DONE
    The Top bar slides away on scroll up. DONE
    User can refresh the playlist with native iOS refreshment on pull down. IN PROGRESS
    User can remove items in bulk in Edit mode. IN PROGRESS
    User can use swipes for:

    Swipe left - for removal of a single item.  IN PROGRESS
    Swipe right - to play summary (needs Player implementation). DEPENDENCY ON PLAYER

    User can listen to an item full version or summarized version for article (needs Player implementation). DEPENDENCY ON PLAYER

**Comment by tamarahills** [comment]
User can see the playlist of articles and Podcasts based on selected topics (preferences). DONE
The Top bar slides away on scroll up. DONE
User can refresh the playlist with native iOS refreshment on pull down. DONE
User can remove items in bulk in Edit mode. DONE
User can use swipes for:

Swipe left - for removal of a single item.  DONE
Swipe right - to play summary (needs Player implementation). DEPENDENCY ON PLAYER

User can listen to an item full version or summarized version for article (needs Player implementation). DEPENDENCY ON PLAYER
