### ISSUE TITLE
Implement Basic Player (no carousel, pause and play only)

### ISSUE THREAD

**Issue by tamarahills** [MozScout/scout-ios#55]

**Comment by Oksanayaz** [comment]
### Acceptance criteria:

1. When User requests to listen to an item, a static Player card is displayed and item is played (if API is OK):

- no carousel
- no animated appearing
- no active progress bar.
2. The only active Player controls are pause and play.

**Comment by tamarahills** [comment]
Stretch goal:  Display image

**Comment by tamarahills** [comment]
When User requests to listen to an item, a static Player card is displayed and item is played (if API is OK):

    no carousel
    no animated appearing
    no active progress bar.
    Showing title, publisher, picture - IN PROGRESS

    The only active Player controls are pause and play. - DONE
