### ISSUE TITLE
Create Subscription Tab

### ISSUE THREAD

**Issue by tamarahills** [MozScout/scout-ios#56]

**Comment by Oksanayaz** [comment]
### Acceptance criteria:
1. User can see a Zero state Subscription tab.
2. On click 'Add' button in the Top bar System opens Podcast directory where User can browse podcast categories.
3. Top categories, besides Top 100 Podcasts are from Onboarding choices by user.

**Comment by tamarahills** [comment]
1. Done
2. In Progress
3.In progress
